[package]
name = "rust_learn"
version = "0.1.0"
authors = ["Hengyu Liang <lhy1210302421@mail.ustc.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

signal-hook = "0.3.8"
regex = "1.4.6"